import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Blurb from "/components/Blurb";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome! </h1>

        <p className={styles.description}>
          <Blurb />
        </p>

        <div className={styles.grid}>
          <a href="https://emmettnaughton.com" className={styles.card}>
            <h2>Read </h2>
            <p>My writing about tech. </p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Listen </h2>
            <p>Podcasts I&#39;ve have been on</p>
          </a>

          <a href="https://github.com/enaughton" className={styles.card}>
            <h2>Learn </h2>
            <p>Discover my projects.</p>
          </a>

          <a
            href="https://hireemmett.work"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Delight</h2>
            <p>What people are saying</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
